### ISSUE TITLE
Update to Rx 4.1.3

### ISSUE THREAD

**Issue by onovotny** [reactiveui/ReactiveUI#1955]
Minor update but has uwp fixes. I also recommend updating to the latest Extras either 1.x or 2.x.

**Comment by glennawatson** [comment]
We are waiting on https://github.com/dotnet/reactive/issues/803 to resolve upstream before we upgrade the minimum version.

Extras we can upgrade.

**Comment by glennawatson** [comment]
Extras portion was addressed by 3ab493eb4c8db17e463911671699af093f52ba4e

**Comment by glennawatson** [comment]
So based on what I'm seeing in that issue it'll be resolved with Visual Studio 2019, so will upgrade the minimum Rx then.

**Comment by giusepe** [comment]
I just tried @PureWeen sample linked in that thread https://github.com/dotnet/reactive/issues/803#issuecomment-414731885
on my VSfM 2019 (8.0 build 1805) and the problem still happens.

Do you know by any chance what build of VSfM has this fixed?

**Comment by glennawatson** [comment]
We upgraded to MSBuild.Sdk.Extras to 2.0.24 recently so that part is covered. Tracking down the offer issues.

**Comment by giusepe** [comment]
Just downloaded the same sample https://github.com/dotnet/reactive/issues/803#issuecomment-414731885 and now it's working with VsfM 8.0.5 (build 9).

Also updated all the nugets and run again: still working, so looks good to me.

**Comment by glennawatson** [comment]
Re-opening since we haven't updated to 4.1.3 yet :)

**Comment by glennawatson** [comment]
Closing this one, will open a task for upgrading to MSBuild.Sdk.Extras
