### ISSUE TITLE
[BUG] WPF: WhenActivated not fired when in ViewModelViewHost

### ISSUE THREAD

**Issue by zperak** [reactiveui/ReactiveUI#2021]
**Describe the bug**
In version __9.14.1__, in commit [a1cb284] MSBuild.Sdk.Extras was updated to v2.0.24 (from 1.6.68). Also `ExtrasEnableWpfProjectSetup` tag is changed to `UseWpf`.
After these two changes in WPF project, `WhenActivated` event does not fire when loaded into `ViewModelViewHost`.
When `MSBuild.Sdk.Extras` is rolled back to version 1.6.68 and `UseWpf` changed back to `ExtrasEnableWpfProjectSetup` in `ReactiveUI.Wpf/ReactiveUI.Wpf.csproj` then everything works again, i.e. this.WhenActivated in view loaded into ViewModelViewHost fires again.

**Steps To Reproduce**
In attached simple WPF project ([DebugWhenActivated.zip](https://github.com/reactiveui/ReactiveUI/files/3161814/DebugWhenActivated.zip)):
1. In App.xaml.css add: `Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.GetCallingAssembly());`
2. In `MainWindow.xaml` add `ViewModelViewHost`
3. In MainWindow.xaml.cs bind `ViewModelViewHost.ViewModel` with `MainDocViewModel` which is `ViewModel` for `MainDocView.xaml` (Reactive)UserControl

**Expected behavior**
1. `ViewModelViewHost` loads `MainDocView.xaml`
2. In `MainDocView.xaml.cs` constructor `this.WhenActivated` is fired

**Actual behavior**
1. The same
2. `this.WhenActivated` is __*not*__ fired

**Environment**
- OS:  Windows 10
- Version 1809
- Device: PC laptop
- IDE: Visual Studio 2019 Enterprise

**Additional context**
To investigate issue, I have added `ReactiveUI` and `ReactiveUI.Wpf` as projects dependencies to my test app (DebugWhenActivated). I had to remove most targets from `ReactiveUI.csproj` to be able to compile project.
You can get the same result if you add dependency via NuGet: Version 9.13.1 works ok and in 9.14.1 `this.WhenActivated` does not work if loaded into `ViewModelViewHost`.

**Comment by glennawatson** [comment]
Will take a look at this one today. Thanks for the detailed report

**Comment by glennawatson** [comment]
Should be fixed in 9.14.3

**Comment by zperak** [comment]
Hi @glennawatson,

I have just tried new version and the problem still exists. `WhenActivated` does not fire when in `ViewModelViewHost`. When `MSBuild.Sdk.Extras` is rolled back to version `1.6.68` everything works fine. 
It must be something in version 2 of `MSBuild.Sdk.Extras`. I tried all available 2.x versions and problem exists with all of them.

**Comment by glennawatson** [comment]
When I ran it with your sample with latest rxui, it was firing and triggering the Console.WriteLine()

**Comment by glennawatson** [comment]
I'm going to reopen it. With the NuGet package getting the same issue. Will work on reverting to 1.6.68 now. Thanks

**Comment by glennawatson** [comment]
Also might be worthwhile opening an issue about this in https://github.com/onovotny/MSBuildSdkExtras/tree/master/Source/MSBuild.Sdk.Extras

**Comment by zperak** [comment]
@glennawatson thanks a lot!

**Comment by zperak** [comment]
Reported to [MSBuildSdkExtras](https://github.com/onovotny/MSBuildSdkExtras): [#162](https://github.com/onovotny/MSBuildSdkExtras/issues/162)

**Comment by onovotny** [comment]
Does this repro with the .NET Core 3 SDK installed?

**Comment by glennawatson** [comment]
Yeah we don't want to go down to having the preview .NET Core in master, so I suspect going back to 1.6.68 and using 2.0.24 in our preview branch is the solution for the moment.

**Comment by glennawatson** [comment]
You may want to change your documentation though for 2.0.24 that it's a requirement of having .net core 3.0

**Comment by onovotny** [comment]
.NET Core 3 is not a requirement, it should fallback to existing behavior if it's not present. That's what I'm trying to determine. I would like to know if it works correctly if it is though.

**Comment by glennawatson** [comment]
Just confirmed his issue does exist if using .NET Core 2.2, but does not exist when using 3.0 preview.

I earlier closed his issue because I was compiling with .NET Core 3.0 preview.

**Comment by glennawatson** [comment]
So the test was done against afdf520a8c5ee7f6bee053af61d7593fad93c2ce and the supplied zip file.

**Comment by onovotny** [comment]
I need more info about the build configuration though...like was the .NET Core 3 SDK installed, etc?

**Comment by glennawatson** [comment]
.NET Core 3 Preview 5, running in Visual STudio 2019 with preview release turned on.

With preview released turned off WhenActivated() does not get triggered.

**Comment by onovotny** [comment]
@glennawatson given that is a WPF specific issue, can you repro it without the extras, with just the WindowsDesktop SDK? If so, that would be a bug for dotnet/wpf

**Comment by glennawatson** [comment]
Will give it a go, one sec.

**Comment by glennawatson** [comment]
I can't even load Microsoft.NET.Sdk.WindowsDesktop without preview turned on. It says 

```
C:\source\reactiveui\ReactiveUI\src\ReactiveUI\ReactiveUI.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
```

**Comment by onovotny** [comment]
Right, I know that. With the preview on, see if you can repro what you saw against the vanilla WPF sdk.

**Comment by glennawatson** [comment]
Ok here's whats happening:

1. With MSBuild.SDk.Extras 2.0.24, no preview turned on, WhenActivated fails 
2. With MsBuild.Sdk.Extras 2.0.24, preview turned on, WhenActivated works
3. With Microsoft.NET.Sdk.WindowsDesktop on the ReactiveUIWPF project, and Microsoft.NET.Sdk on the ReactiveUI project, preview turned on, WhenActivatedWorks
4. With MsBuild.Sdk.Extras 1.6.68, WhenActivatedWorks
5. With Microsoft.NET.Sdk.WindowsDesktop set on both ReactiveUI.WPF  and ReactiveUI projects, I get the error ` The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized`

**Comment by onovotny** [comment]
Can you please get me a binlog from scenario 1?

**Comment by glennawatson** [comment]
Those are the binlogs for the two assemblies he had in his demo.

BTW I am no longer in the US time zone so things are a bit delayed.
[binlog.zip](https://github.com/reactiveui/ReactiveUI/files/3175075/binlog.zip)

**Comment by onovotny** [comment]
You have to stop collecting those binlogs. They contain secrets!

**Comment by glennawatson** [comment]
Ok thanks made the change.

**Comment by onovotny** [comment]
Looking at the binlog, nothing immediately jumps out at me. I can see that it's not importing the WindowsDesktop targets, by design, as they're not found (correctly). It's using the 2.2.x SDK to build.

I can see the Microsoft.WinFX.targets being imported by the common targets. I'm not sure what's going on here.

What I can say is this.... if it works with the .NET Core 3 Preview SDK & VS 2019, then that's my primary goal. I want to leverage as much as the built-in targets allow, and that SDK allows/supports building .NET Framework and .NET Core WPF correctly. If there's an issue there, I'd be concerned.

If, as it seems, the issue is limited to VS 2019 and the 2.2 SDK, I don't have a lot of time to spend on digging. I'll take a PR if someone can figure out what's going on though.

**Comment by glennawatson** [comment]
Sure, we will just stick with 1.6.68 in master for the moment. My goal is to go to .net core 3.0 as soon as it's released.

**Comment by onovotny** [comment]
I frankly don't see an issue with using the preview SDK to build the binaries...but that's up to you.
